# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fheartbeat.proto\x12\theartbeat\"\x18\n\x07\x43ounter\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32@\n\tHeartBeat\x12\x33\n\x05\x42\x65\x61ts\x12\x12.heartbeat.Counter\x1a\x12.heartbeat.Counter\"\x00\x30\x01\x62\x06proto3')



_COUNTER = DESCRIPTOR.message_types_by_name['Counter']
Counter = _reflection.GeneratedProtocolMessageType('Counter', (_message.Message,), {
  'DESCRIPTOR' : _COUNTER,
  '__module__' : 'heartbeat_pb2'
  # @@protoc_insertion_point(class_scope:heartbeat.Counter)
  })
_sym_db.RegisterMessage(Counter)

_HEARTBEAT = DESCRIPTOR.services_by_name['HeartBeat']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COUNTER._serialized_start=30
  _COUNTER._serialized_end=54
  _HEARTBEAT._serialized_start=56
  _HEARTBEAT._serialized_end=120
# @@protoc_insertion_point(module_scope)
