# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\"\x18\n\x08HelloReq\x12\x0c\n\x04Name\x18\x01 \x01(\t\"\x1b\n\tHelloResp\x12\x0e\n\x06Result\x18\x01 \x01(\t2v\n\x0cHelloService\x12/\n\x08sayHello\x12\x0f.hello.HelloReq\x1a\x10.hello.HelloResp\"\x00\x12\x35\n\x0esayHelloStrict\x12\x0f.hello.HelloReq\x1a\x10.hello.HelloResp\"\x00\x62\x06proto3')



_HELLOREQ = DESCRIPTOR.message_types_by_name['HelloReq']
_HELLORESP = DESCRIPTOR.message_types_by_name['HelloResp']
HelloReq = _reflection.GeneratedProtocolMessageType('HelloReq', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQ,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloReq)
  })
_sym_db.RegisterMessage(HelloReq)

HelloResp = _reflection.GeneratedProtocolMessageType('HelloResp', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESP,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloResp)
  })
_sym_db.RegisterMessage(HelloResp)

_HELLOSERVICE = DESCRIPTOR.services_by_name['HelloService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQ._serialized_start=22
  _HELLOREQ._serialized_end=46
  _HELLORESP._serialized_start=48
  _HELLORESP._serialized_end=75
  _HELLOSERVICE._serialized_start=77
  _HELLOSERVICE._serialized_end=195
# @@protoc_insertion_point(module_scope)
